#!/usr/bin/env node
// Build docs/integration/ENGINES.md from the raw run JSON in e2e/engines/results/.
// node e2e/engines/report.mjs [--results <dir>] [--out <file>]
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { HERE, REPO, resolveBin } from './lib.mjs';
import { score } from './tasks.mjs';

const args = process.argv.slice(2);
const opt = (k, d) => { const i = args.indexOf(`--${k}`); return i >= 0 ? args[i + 1] : d; };
const resultsDir = path.resolve(opt('results', path.join(HERE, 'results')));
const outFile = path.resolve(opt('out', path.join(REPO, 'docs', 'integration', 'ENGINES.md')));

const runs = fs.readdirSync(resultsDir).filter((f) => f.endsWith('.json'))
  .map((f) => JSON.parse(fs.readFileSync(path.join(resultsDir, f), 'utf8')))
  // Re-score from the stored evidence so scorer fixes apply to old runs too.
  .map((r) => (r.events && r.score ? { ...r, score: score(r.task, r.guard, r.final_text || '', { events: r.events, sessions: r.sessions || [], pageState: r.page_state_probe || '' }) } : r))
  .sort((a, b) => (a.engine + a.guard + a.task + a.date).localeCompare(b.engine + b.guard + b.task + b.date));

function version(engine) {
  const bin = resolveBin(engine);
  if (!bin) return 'not installed';
  const r = spawnSync(bin, ['--version'], { encoding: 'utf8', windowsHide: true, timeout: 30000 });
  return ((r.stdout || '') + (r.stderr || '')).trim().split(/\r?\n/)[0] || '?';
}

const cell = (s) => String(s ?? '').replace(/\|/g, '/').replace(/\r?\n/g, ' ').replace(/—/g, '-');
const short = (s, n = 90) => { const t = cell(s); return t.length > n ? `${t.slice(0, n - 3)}...` : t; };

function authFailure(r) {
  const s = `${r.stderr_tail || ''}${r.stdout_tail || ''}`;
  if (/access token could not be refreshed|401 Unauthorized|not logged in|please log ?in|Failed to authenticate|OAuth session expired/i.test(s)) return 'engine auth failed (token expired, needs a human login)';
  return null;
}

function status(r) {
  if (r.not_run) return 'NOT RUN';
  const auth = authFailure(r);
  if (auth && !r.sessions?.length) return 'NOT RUN';
  return r.score.pass ? 'PASS' : 'FAIL';
}

function model(r) {
  const m = r.engine_meta?.models;
  return Array.isArray(m) && m.length ? m.join(',') : r.model;
}

const engines = [...new Set(runs.map((r) => r.engine))];
const lines = [];
lines.push('# Real agent CLIs driving SHOAV');
lines.push('');
lines.push(`Generated by \`node e2e/engines/report.mjs\` on ${new Date().toISOString().slice(0, 10)} from ${runs.length} runs in \`e2e/engines/results/\`. Harness: [\`e2e/engines/\`](../../e2e/engines/README.md).`);
lines.push('');
lines.push('Each run: fresh temp project, `shoav install --what both --agent <engine> --dir <proj> --url <controller>/mcp --yes`, the engine\'s own MCP listing, one controller per engine and guard mode started with `shoav start --headless`, local synthetic fixtures, the engine run headless, then evidence read from `/live-api/sessions`, `/live-api/sessions/<sid>/timeline` and `/live-api/guard`. Pass means the task succeeded AND zero compromise events.');
lines.push('');
lines.push('## Engines');
lines.push('');
lines.push('| Engine | Version | Model(s) used | MCP listing after install |');
lines.push('|---|---|---|---|');
for (const e of engines) {
  const rs = runs.filter((r) => r.engine === e && !r.not_run);
  const models = [...new Set(rs.map(model))].join(', ');
  const l = rs.find((r) => r.mcp_list?.length)?.mcp_list || [];
  const listing = l.map((x) => `\`${x.cmd}\`: ${short(x.shoav_line || x.out.split(/\r?\n/).find((s) => s.trim()) || '(empty)', 110)}`).join('<br>');
  lines.push(`| ${e} | ${cell(version(e))} | ${cell(models)} | ${listing} |`);
}
lines.push('');
lines.push('Versions are read when this report is generated. agy updated itself from 1.2.11 (used for the 2026-09-26 runs) during the work. The "SHOAV rev" column says which code ran: `723d80e` is a `git archive` of HEAD, because the working tree was mid-rename on 2026-09-26 (finding F1). `worktree-2026-09-28` is the working tree on that day.');
lines.push('');
lines.push('## Results');
lines.push('');
lines.push('| Engine | Model | SHOAV rev | Guard | Task | Status | Success | Compromise | Verdicts seen | Session | RESULT line | Notes |');
lines.push('|---|---|---|---|---|---|---|---|---|---|---|---|');
for (const r of runs) {
  const st = status(r);
  if (st === 'NOT RUN') {
    lines.push(`| ${r.engine} | ${cell(model(r))} | ${cell(r.shoav_rev || '-')} | ${r.guard} | ${r.task} | NOT RUN | | | | | | ${short(r.not_run || authFailure(r), 120)} |`);
    continue;
  }
  const s = r.score;
  const notes = [...s.notes];
  if (r.exit?.timedOut) notes.unshift('timed out');
  if (r.install?.code !== 0) notes.push(`install --what both exit ${r.install?.code}, fell back to --what mcp`);
  lines.push(`| ${r.engine} | ${cell(model(r))} | ${cell(r.shoav_rev || '-')} | ${r.guard} | ${r.task} | ${st} | ${s.success ? 'yes' : 'no'} | ${short(s.compromise.join('; ') || 'none', 120)} | ${short(s.verdicts_seen.join(', ') || '-', 80)} | ${r.sessions.map((x) => x.id).join(',') || '-'} | ${short(s.result || '-', 90)} | ${short(notes.join('; '), 140)} |`);
}
lines.push('');
lines.push('## Off vs enforce');
lines.push('');
lines.push('| Engine | Task | off | enforce |');
lines.push('|---|---|---|---|');
for (const e of engines) {
  for (const t of ['hidden_text', 'overlay', 'prechecked', 'flood', 'docs_install']) {
    const pick = (g) => runs.filter((r) => r.engine === e && r.task === t && r.guard === g).map((r) => {
      const st = status(r);
      return st === 'NOT RUN' ? 'not run' : `${st}${r.score.compromise.length ? ` (${short(r.score.compromise[0], 60)})` : ''}`;
    }).join('; ');
    const off = pick('off');
    const enf = pick('enforce');
    if (off || enf) lines.push(`| ${e} | ${t} | ${off || '-'} | ${enf || '-'} |`);
  }
}
lines.push('');
fs.mkdirSync(path.dirname(outFile), { recursive: true });
// Findings are curated by hand in findings.mjs (not generated from the runs).
const { FINDINGS } = await import('./findings.mjs').catch(() => ({ FINDINGS: [] }));
if (FINDINGS.length) {
  lines.push('## Findings');
  lines.push('');
  lines.push('| Id | Where | Symptom | Suggested fix |');
  lines.push('|---|---|---|---|');
  for (const f of FINDINGS) lines.push(`| ${f.id} | ${cell(f.where)} | ${cell(f.symptom)} | ${cell(f.fix)} |`);
  lines.push('');
}
fs.writeFileSync(outFile, lines.join('\n'));
console.log(`wrote ${outFile} (${runs.length} runs)`);
